// ipc
export const IPCLOGINSUCCESS = "IPCLOGINSUCCESS";
export const IPCLOGINERROR = "IPCLOGINERROR";



//pubsub
export const LOGINSUCCESS = "LOGINSUCCESS";
export const STARTINVITE = "STARTINVITE";